FROM alpine

RUN apk add && \
    apk add build-base libffi-dev libsodium openssl-dev python3-dev

WORKDIR /app
COPY py/requirements.txt .
RUN pip3 install -r requirements.txt

COPY py/*.py ./

WORKDIR /templates
COPY templates/* ./

WORKDIR /static
COPY static/* ./

WORKDIR /app
